name: Generate Documentation

# Triggers the workflow on pull request events but only for the main branch
# Build is triggered with successful push of a new Tag (No need to initiate the build manually via github)
on:
  push:
    branches:
      - main

jobs:
  generate_documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Generate documentation
        run: dart pub global run dartdoc

      - name: Commit and deploy to gh-pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout --orphan gh-pages
          git rm -rf .
          cp -R doc/api/* .
          git add .
          git commit -m "Update Flutter documentation"
          git push origin gh-pages --force