name: Deploy Flutter Docs

on:
  push:
    branches:
      - main  # Replace with your default branch

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Install dartdoc
        run: |
          dart pub global activate dartdoc
          echo "::add-path::${HOME}/.pub-cache/bin"

      - name: Verify dartdoc installation
        run: dartdoc --version

      - name: Generate documentation
        run: dartdoc

      - name: Commit and deploy to gh-pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch origin gh-pages
          git switch gh-pages || git checkout --orphan gh-pages
          git rm -rf ./*
          cp -R doc/api/* .
          git add .
          git commit -m "Update Flutter documentation" || echo "No changes to commit"
          git push origin gh-pages
